### ISSUE TITLE
当字段有下划线的时候会过滤掉字段的下划线 

### ISSUE THREAD

**Issue by zengpengkindle** [crazywolfcode/CodeGenerater#2]
![image](https://user-images.githubusercontent.com/16894507/51306473-6090a280-1a78-11e9-8bb9-877b37c70ccc.png)
你的sqlhelp是dll可否提供下源码

**Comment by crazywolfcode** [comment]
https://www.nuget.org/packages/SqlDao/ 这里面有，

**Comment by crazywolfcode** [comment]
clone https://github.com/crazywolfcode/SqlDaoDemo.git 源码地址
